- name: Install packages
  dnf:
    name:
      # - gnome-tweak-tool
      - gnome-extensions-app
      - telnet
      - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - openfortivpn
      - jq
      - groovy
      - dnf-plugins-core
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - ansible
#- name: Configure Openfortivpn host
#  dconf:
#    key: /etc/openfortivpn/config/host
#    value: "vpnportal.albelli.net"
#- name: Configure Openfortivpn port
#  dconf:
#    key: /etc/openfortivpn/config/port
#    value: "443"
#- name: Configure Openfortivpn username
#  dconf:
#    key: /etc/openfortivpn/config/username
#    value: "avallecilla@albelli.net"
